version: '3'

services:
  web:
    build: 
      context: .
      dockerfile: ./Dockerfile
    image: my-django:1.0
    command: python ./mysite/manage.py runserver 0.0.0.0:8000
    volumes:
      - ./mysite:/usr/src/app/mysite
    ports:
      - 8000:8000

networks:
  default:
    name: hy22-external-network
    external: true