version: '3'

services:

#influxDB
  influxdb:
    image: influxdb:1.8.6
    container_name: influxDB
    ports:
      - 8086:8086 #influxDB 기본
      # - 8088:8088 #백업 및 복원 위해
    # environment:
    #   - INFLUXDB_ADMIN_USER_PASSWORD=bitnami123
    #   - INFLUXDB_ADMIN_USER_TOKEN=admintoken123
    volumes:
      - ./data/influxdb:/var/lib/influxdb

#mongoDB
  mongodb:
    image: bitnami/mongodb:5.0
    container_name: mongodb
    ports:
      - "27017:27017" #mongoDB 기본
    volumes:
      - ./data/mongodb:/bitnami/mongodb

  postgresql:
    image: bitnami/postgresql:10
    volumes:
      - ./data/postgresql:/bitnami/postgresql
    environment:
      - POSTGRESQL_DATABASE=bitnami_airflow
      - POSTGRESQL_USERNAME=bn_airflow
      - POSTGRESQL_PASSWORD=bitnami1
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes

  redis:
    image: docker.io/bitnami/redis:6.0
    volumes:
      # - ./data/redis:/docker_sona
      - ./data/redis:/bitnami/redis/data
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes

networks: 
  default: 
    external: 
      name: hy22-external-network