version: '3'

services:

# 스파크
# 스파크 마스터
  spark-master:
    image: spark-hyunjinee:0.1
    container_name: spark-master
    ports:
      - 8080:8080 # master webui
      - 7077:7077 # master port
    environment:
      - SPARK_MODE=master
      - SPARK_MASTER_HOST=spark-master
      - SPARK_MASTER_PORT=7077
      - SPARK_MASTER_WEBUI_PORT=8080
    volumes: 
      - ./asstes/spark:/spark-work

# 스파크 워커2개
  spark-worker:
    image: spark-hyunjinee:0.1
    container_name: spark-worker-1
    scale: 1
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_HOST=spark-master
      - SPARK_MASTER_PORT=7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
    ports:
      - 18080:8082
    # volumes:
    #   - shared-workspace:/opt/workspace
    depends_on:
      - spark-master

  zeppelin:
    image: apache/zeppelin:0.10.1
    container_name: zeppelin
    scale: 1
    environment:
      # - SPARK_MODE=zeppelin
      # - SPARK_MASTER_HOST=spark-master
      # - SPARK_MASTER_PORT=7077
      # - ZEPPELIN_ADDR=0.0.0.0
      - ZEPPELIN_LOG_DIR='/logs'
      - ZEPPELIN_NOTEBOOK_DIR='/notebook'
    ports:
      - 18090:8080
    volumes:
      - ./data/zeppelin/logs:/logs
      - ./data/zeppelin/data:/data
      - ./data/zeppelin/notebook:/notebook
    # depends_on:
    #   - spark-master

networks: 
  default: 
    external: 
      name: hy22-external-network