version: '3'

services:

  influxdb:
    image: influxdb:1.8.6
    container_name: influxdb
    ports:
      - 8086:8086 #influxDB 기본
      # - 8088:8088 #백업 및 복원 위해
    # environment:
    #   - INFLUXDB_ADMIN_USER_PASSWORD=bitnami123
    #   - INFLUXDB_ADMIN_USER_TOKEN=admintoken123
    volumes:
      - ./data/influxdb:/var/lib/influxdb

#mongoDB
  mongodb:
    image: mongo
    restart: always
    container_name: mongodb
    environment:
      # MONGODB_ROOT_PASSWORD: example
      MONGODB_DATABASE: LiveCommerce
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
    volumes:
      - ./data/mongo:/data/db
    ports:
      - "27017:27017"

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 19082:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_ROOT_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_ROOT_USERNAME}:${MONGO_ROOT_PASSWORD}@${MONGODB_HOST}/


# networks:
#   default:
#     name: hy22-external-network
#     external: true

networks:

  hy22-external-network : 
    external: true
