version: '3'

services:

#influxDB
  influxdb:
    image: influxdb:1.8.6
    container_name: influxDB
    ports:
      - 8086:8086 #influxDB 기본
      # - 8088:8088 #백업 및 복원 위해
    # environment:
    #   - INFLUXDB_ADMIN_USER_PASSWORD=bitnami123
    #   - INFLUXDB_ADMIN_USER_TOKEN=admintoken123
    volumes:
      # - influxdb_data:/docker_sona/influxdb 
      - "/data/influxdb:/docker_sona/influxdb"

#mongoDB
  mongodb:
    image: docker.io/bitnami/mongodb:5.0
    container_name: mongoDB
    ports:
      - "27017:27017" #mongoDB 기본
    volumes:
      - './mongodb_data:/docker_sona/mongodb'


#airflow & PostgreSQL & Redis
#캐싱전략?? https://rumor1993.tistory.com/m/86
#Airflow 컨테이너 - PostgreSQL와 Redis에 의존하여 데이터를 유지
#데이터 손실을 방지하려면 PostgreSQL 데이터 및 Redis(TM) 데이터의 지속성을 위해 볼륨을 마운트
  postgresql:
    image: docker.io/bitnami/postgresql:10
    volumes:
      - './postgresql_data:/docker_sona/postgresql'
    environment:
      - POSTGRESQL_DATABASE=bitnami_airflow
      - POSTGRESQL_USERNAME=bn_airflow
      - POSTGRESQL_PASSWORD=bitnami1
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes

  redis:
    image: docker.io/bitnami/redis:6.0
    volumes:
      - './redis_data:/docker_sona'   
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
