version: '3'

services:

# 주키퍼
  zookeeper:
    image: zookeeper:3.6.0
    container_name: zookeeper
    ports:
      - "2181:2181"
    volumes:
      - ./data/zookeeper/data:/data
      - ./data/zookeeper/logs:/datalog

# 카프카 -standalone
  kafka:
    container_name: kafka
    image: wurstmeister/kafka:latest 
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_HOST_NAME= 127.0.0.1
      - KAFKA_ADVERTISED_PORT= 9092
      - KAFKA_CREATE_TOPICS= "test_topic:1:1" # Topic명:Partition개수:Replica개수
      - KAFKA_ZOOKEEPER_CONNECT= zookeeper:2181
    volumes:
      - ./data/kafka/logs:/opt/kafka/logs
      - ./data/kafka/data:/kafka

# git clone https://github.com/linkedin/Burrow
  burrow: 
    # build:
    #   context: .
    #   dockerfile: ./Burrow/Dockerfile
    image: hy22-burrow:0.1
    volumes:
      - ./burrow_docker/docker-config:/etc/burrow/

    ports:
      - 8000:8000
    depends_on:
      - kafka
    restart: always
