version: '3'

services:

  py-producer:
    image: py-docker:0.1
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    environment:
      - KAFKA_SERVER=${KAFKA_SERVER:-kafka:9092}
    volumes:
      - ../crwaling:/usr/src/app
    command: python3 ./test_main.py
    # command: bash


networks:
  hy22-external-network :
    driver: bridge
    external: true
    internal: true


# networks:
#   default:
#     name: hy22-external-network
#     external: true

# networks:
#   hy22-external-network : 
#     external: true