version: '3'

services:

# 스파크
# 스파크 마스터
  spark-master-sona:
    build:
      context: .
      dockerfile: ./assets/spark/Dockerfile 
    image: my-spark:0.2
    container_name: spark-master-sona
    ports:
      - 18083:18083 # master webui
      - 17077:17077 # master port
    environment:
      - SPARK_MODE=master
      - SPARK_MASTER_HOST=spark-master-sona
      - SPARK_MASTER_PORT=17077
      - SPARK_MASTER_WEBUI_PORT=18083
      - NVIDIA_VISIBLE_DEVICE=0
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]


    volumes: 
      - ./assets/spark:/spark-work
    networks:
      - hy22-external-network

# 스파크 워커1개
  spark-worker-sona:
    build:
      context: .
      dockerfile: ./assets/spark/Dockerfile 
    image: my-spark:0.2
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER=spark://spark-master:17077
      - SPARK_WORKER_MEMORY=2G
      - SPARK_WORKER_CORES=1
      - NVIDIA_VISIBLE_DEVICE=0
    deploy:
      replicas: 1
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]    
    depends_on:
      - spark-master-sona
    networks:
      - hy22-external-network

networks:
  hy22-external-network :
    driver: bridge
    external: true
    internal: true

