version: '3'

services:

#grafana & grafana 렌더링
#grafana
  grafana:
    image: docker.io/bitnami/grafana:8
    container_name: grafana
    ports:
      - '3000:3000' #grafana 기본
    # environment:
    #   - 'GF_SECURITY_ADMIN_PASSWORD=bitnami'
    volumes:
      - './data/grafana:/opt/bitnami/grafana/data'



#그라파나 이미지렌더링
#=> chrome 사용해서 패널과 대시보드를 png이미지로 랜더링
  grafana-image-renderer:
    image: docker.io/bitnami/grafana-image-renderer:3
    # ports:
    #   - '8081:8081'
    # environment:
    #   HTTP_HOST: "0.0.0.0"
    #   HTTP_PORT: "8080"
    #   ENABLE_METRICS: 'true' 

networks:
  default:
    name: hy22-external-network
    external: true