version: '3'

services:

  spark-master:
    extends:
      file: docker-compose-spark.yml
      service: spark-master

  spark-worker:
    extends:
      file: docker-compose-spark.yml
      service: spark-worker

  zeppelin:
    extends:
      file: docker-compose-spark.yml
      service: zeppelin

  zookeeper:
    extends:
      file: docker-compose-kafka.yml
      service: zookeeper

  kafka:
    extends:
      file: docker-compose-kafka.yml
      service: kafka

