version: '3'

services:

# 스파크
# 스파크 마스터
  spark-master-sona:
    build:
      context: .
      dockerfile: ./assets/spark/Dockerfile 
    image: sona-spark:0.3
    container_name: spark-master-sona
    ports:
      - 18083:8080 # master webui
      - 17077:7077 # master port
    environment:
      - SPARK_MODE=master
      - SPARK_MASTER_HOST=spark-master-sona
      - SPARK_MASTER_PORT=7077
      - SPARK_MASTER_WEBUI_PORT=8080
      - NVIDIA_VISIBLE_DEVICE=0
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

    volumes: 
      - ./assets/spark:/spark-work
      - ./assets/model:/spark-work/model
      - ./assets/spark/conf:/opt/spark/conf
    networks:
      - hy22-external-network


# 스파크 워커333개
  spark-worker-sona:
    build:
      context: .
      dockerfile: ./assets/spark/Dockerfile 
    image: sona-spark:0.3
    # container_name: spark-worker-sona
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER=spark://spark-master-sona:7077
      - SPARK_WORKER_MEMORY=2G
      - SPARK_WORKER_CORES=3
      - NVIDIA_VISIBLE_DEVICE=0
    deploy:
      replicas: 1
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]    
    depends_on:
      - spark-master-sona
    volumes: 
      # - ./assets/spark:/spark-work
      # - ./assets/model:/spark-work/model
      - ./assets/spark/conf:/opt/spark/conf

    networks:
      - hy22-external-network

networks:
  hy22-external-network :
    driver: bridge
    external: true
    internal: true

