version: '3'

services:

# 주키퍼
  zookeeper:
    image: zookeeper:3.6.0
    container_name: zookeeper
    ports:
      - "2181:2181"
    volumes:
      - ./data/zookeeper/data:/data
      - ./data/zookeeper/logs:/datalog
    # networks:
    #   - hy22-external-network

# 카프카 -standalone
  kafka:
    build: 
      context: .
      dockerfile: ./assets/kafka/Dockerfile
    container_name: kafka
    image: my-kafka:0.1
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      - KAFKA_ADVERTISED_HOST_NAME= kafka
      - KAFKA_ADVERTISED_PORT= 9092
      - KAFKA_CREATE_TOPICS= "test_topic:1:1" # Topic명:Partition개수:Replica개수
      - KAFKA_ZOOKEEPER_CONNECT= zookeeper:2181
      - KAFKA_BROKER_ID=1
      - KAFKA_OPTS= -javaagent:/usr/app/jmx_prometheus_javaagent.jar=7071:/usr/app/prom-jmx-agent-config.yml
    volumes:
      - ./data/kafka/logs:/opt/kafka/logs
      - ./data/kafka/data:/kafka
      - /var/run/docker.sock:/var/run/docker.sock
    # extra_hosts:
    #   - kafka:20.232.136.207
    #   - mongodb:20.232.136.207

    # networks:
    #   - hy22-external-network

networks:
  default:
    name: hy22-external-network
    external: true

# networks:
#   hy22-external-network :
#     driver: bridge
#     external: true
#     internal: true
