version: '2'

services:
  grafana:
    image: grafana/grafana-oss:8.2.0
    ports:
      - 3000:3000
    volumes:
      - ./data/grafana:/var/lib/grafana

networks:
  default:
    name: hy22-external-network
    external: true

volumes:
  grafana-volume:
    external: true