version: '3'

services:

# 스파크
# 스파크 마스터
  spark-master:
    image: my-spark:0.1
    container_name: spark-master
    ports:
      - 8080:8080 # master webui
      - 7077:7077 # master port
    environment:
      - SPARK_MODE=master
      - SPARK_MASTER_HOST=spark-master
      - SPARK_MASTER_PORT=7077
      - SPARK_MASTER_WEBUI_PORT=8080
    volumes: 
      - ./assets/spark:/spark-work

# 스파크 워커2개
  spark-worker:
    image: my-spark:0.1
    scale: 2
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_HOST=spark-master
      - SPARK_MASTER_PORT=7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
    # ports:
    #   - 18080:8082
    # volumes:
    #   - shared-workspace:/opt/workspace
    depends_on:
      - spark-master

  zeppelin:
    build:
      context: .
      dockerfile: ./assets/zeppelin/docker/Dockerfile  
    image: my-zeppelin:0.1
    container_name: zeppelin
    environment:
      - ZEPPELIN_PORT=8080
      - ZEPPELIN_LOG_DIR=/logs
      - ZEPPELIN_NOTEBOOK_DIR=/notebook
      - SPARK_MASTER=spark://spark-master:7077
      - USE_HADOOP=false
    ports:
      - 18090:8080
    volumes:
      - ./data/zeppelin/logs:/logs
      - ./data/zeppelin/data:/data
      - ./assets/zeppelin/notebook:/notebook
      - ./assets/zeppelin/conf:/opt/zeppelin/conf


networks: 
  default: 
    external: 
      name: hy22-external-network