version: '3'

services:

  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes: 
      - ./assets/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - hy22-external-network


networks:
  hy22-external-network :
    driver: bridge
    external: true
    internal: true

