version: '3'

services:

# 스파크
# 스파크 마스터
  # spark-master:
  #   build:
  #     context: .
  #     dockerfile: ./assets/spark/Dockerfile 
  #   image: my-spark:0.3
  #   container_name: spark-master
  #   ports:
  #     - 8080:8080 # master webui
  #     - 7077:7077 # master port
  #   environment:
  #     - SPARK_MODE=master
  #     - SPARK_MASTER_HOST=spark-master
  #     - SPARK_MASTER_PORT=7077
  #     - SPARK_MASTER_WEBUI_PORT=8080
  #     - NVIDIA_VISIBLE_DEVICE=0
  #   deploy:
  #     resources:
  #       reservations:
  #         devices:
  #           - driver: nvidia
  #             count: 1
  #             capabilities: [gpu]

  #   volumes: 
  #     - ./assets/spark:/spark-work
  #     - ./assets/model:/spark-work/model
  #     - ./assets/spark/conf:/opt/spark/conf
  #   networks:
  #     - hy22-external-network


# 스파크 워커 1개
  spark-worker:
    build:
      context: .
      dockerfile: ./assets/spark/Dockerfile 
    image: my-spark:0.3
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=2G
      - SPARK_WORKER_CORES=2
      - NVIDIA_VISIBLE_DEVICE=0
    deploy:
      replicas: 1
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]    
    depends_on:
      - spark-master
    volumes: 
      # - ./assets/spark:/spark-work
      # - ./assets/model:/spark-work/model
      - ./assets/spark/conf:/opt/spark/conf

    networks:
      - hy22-external-network

    extra_hosts:
      - "spark-master:20.232.136.207"
      - "kafka:20.232.136.207"
      - "influxdb:20.232.136.207"
      - "mongodb:20.232.136.207"


networks:
  hy22-external-network :
    driver: bridge
    external: true
    internal: true