version: '2'

services:
  influxdb:
    image: influxdb:1.7
    container_name: influxdb_default
    ports:
      - 8086:8086
    volumes:
      - ./data/influxdb:/var/lib/influxdb
    networks:
      - hy22-external-network

networks:
  default:
    name: hy22-external-network
    external: true
    internal: true

# networks:
#   hy22-external-network :
#     driver: bridge
#     external: true
#     internal: true


