version: '3'

services:

# 스파크
# 스파크 마스터
  spark-master:
    image: my-spark:0.1
    container_name: spark-master
    ports:
      - 8080:8080 # master webui
      - 7077:7077 # master port
    environment:
      - SPARK_MODE=master
      - SPARK_MASTER_HOST=spark-master
      - SPARK_MASTER_PORT=7077
      - SPARK_MASTER_WEBUI_PORT=8080
    volumes: 
      - ./assets/spark:/spark-work

# 스파크 워커2개
  spark-worker:
    image: my-spark:0.1
    deploy:
      replicas: 2
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_HOST=spark-master
      - SPARK_MASTER_PORT=7077
      - SPARK_WORKER_MEMORY=2G
      - SPARK_WORKER_CORES=2
    # ports:
    #   - 18080:8082
    # volumes:
    #   - shared-workspace:/opt/workspace
    depends_on:
      - spark-master

  zeppelin:
<<<<<<< HEAD
    # build:
    #   context: .
    #   dockerfile: ./assets/zeppelin/docker/Dockerfile  
    # image: my-zeppelin:0.1
=======
>>>>>>> 79d683318145c82857bddd8e5f45fcbe8a20512d
    image: my-spark:0.1
    container_name: zeppelin
    environment:
      - SPARK_MODE=zeppelin
<<<<<<< HEAD
      - ZEPPELIN_PORT=8080
=======
      # - ZEPPELIN_PORT=8080
>>>>>>> 79d683318145c82857bddd8e5f45fcbe8a20512d
      - ZEPPELIN_LOG_DIR=/logs
      - ZEPPELIN_NOTEBOOK_DIR=/notebook
      - SPARK_MASTER=spark://spark-master:7077
      # - USE_HADOOP=false
      # - SPARK_SUBMIT_OPTIONS=--total-executor-cores 4 --name zeppelin
    ports:
      - 18090:8080
    volumes:
      - ./data/zeppelin/logs:/logs
      - ./assets/notebook:/notebook

<<<<<<< HEAD
=======
    depends_on:
      - spark-master

>>>>>>> 79d683318145c82857bddd8e5f45fcbe8a20512d
networks:
  default:
    name: hy22-external-network
    external: true