global:
  scrape_interval: 10s

  external_labels:
    monitor: 'spark-monitor'

scrape_configs:

  - job_name: 'integrations/spark-master'
    scrape_interval: 10s
    metrics_path: '/metrics/master/prometheus'
    static_configs:
      - targets: ['spark-master-sona:8080']
        labels:
          instance_type: 'master'
          spark_cluster: 'my-cluster'
  - job_name: 'integrations/spark-worker'
    scrape_interval: 10s
    metrics_path: '/metrics/prometheus'
    static_configs:
      - targets: ['spark-worker-sona:8081']
        labels:
          instance_type: 'worker'
          spark_cluster: 'my-cluster'
  # - job_name: 'integrations/spark-driver'
  #   scrape_interval: 10s
  #   metrics_path: '/metrics/prometheus/'
  #   static_configs:
  #     - targets: ['spark-driver:4040']
  #       labels:
  #         instance_type: 'driver'
  #         spark_cluster: 'my-cluster'