global:
  scrape_interval: 10s
  evaluation_interval: 10s

  external_labels:
    monitor: 'spark-monitor'

scrape_configs:

  - job_name: 'integrations/spark-master'
    scrape_interval: 10s
    metrics_path: '/metrics/master/prometheus'
    static_configs:
      - targets: ['spark-master:8080']
        labels:
          instance_type: 'master'
          spark_cluster: 'my-cluster'
  - job_name: 'integrations/spark-worker'
    scrape_interval: 10s
    metrics_path: '/metrics/prometheus'
    static_configs:
      - targets: ['pipeline-spark-worker-1:8081','pipeline-spark-worker-2:8081','pipeline-spark-worker-3:8081']
        labels:
          instance_type: 'worker'
          spark_cluster: 'my-cluster'
  - job_name: 'kafka'
  # metrics_path defaults to '/metrics'
  # scheme defaults to 'http'.
    static_configs:
      - targets: ['kafka:7071']
  # - job_name: 'integrations/spark-driver'
  #   scrape_interval: 10s
  #   metrics_path: '/metrics/prometheus/'
  #   static_configs:
  #     - targets: ['spark-driver:4040']
  #       labels:
  #         instance_type: 'driver'
  #         spark_cluster: 'my-cluster'